language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - 1.8.x
  - tip
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint
  - dep ensure
jobs:
  include:
    - stage: code_style
    - script: golint -set_exit_status && go vet
    - stage: test
    - script: go test -race -coverprofile=profile.out -covermode=atomic && cat profile.out >> coverage.txt && rm profile.out

after_success:
- bash <(curl -s https://codecov.io/bash)
